# Generated by Django 4.2.13 on 2025-07-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_description_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquery',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Fulfilled', 'Fulfilled')], default='Order Placed', max_length=20),
        ),
    ]
