# Generated by Django 4.2.13 on 2025-07-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_supportquery_response_alter_order_status'),
    ]

    operations = [
    ]
